// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"ConfusionExtend","status":true,"description":"混乱ステート拡張プラグイン","parameters":{"List":"[\"{\\\"StateId\\\":\\\"35\\\",\\\"SkillList\\\":\\\"[]\\\",\\\"UsableSkill\\\":\\\"true\\\",\\\"LastSkill\\\":\\\"false\\\",\\\"SkillFilterList\\\":\\\"[]\\\",\\\"SpareSkill\\\":\\\"0\\\",\\\"TargetActorId\\\":\\\"0\\\",\\\"TargetEnemyId\\\":\\\"0\\\",\\\"TargetIndex\\\":\\\"0\\\",\\\"LastTarget\\\":\\\"false\\\",\\\"RemoveUser\\\":\\\"true\\\"}\"]"}}
];
